name: Publish to NPM

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: "contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Publish All Packages
        run: pnpm publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git Tag
        run: |
          TAG_NAME="release/$(date +'%Y-%m-%d-%H%M')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Summary
        run: |
          echo "### 🚀 Publication Successful" >> $GITHUB_STEP_SUMMARY
          echo "Changed packages have been published to NPM." >> $GITHUB_STEP_SUMMARY
          echo "A new release tag has been created." >> $GITHUB_STEP_SUMMARY
